name: Pre-commit Hooks

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      SKIP: golangci-lint,no-commit-to-branch
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
